name: Type

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  type:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install mypy
        pip install -r requirements.txt
    - name: Check with mypy
      run: mypy ./universelist --strict
